### ISSUE TITLE
Preserve key order

### ISSUE THREAD

**Issue by Tarang** [rhalff/dot-object#1]
If I have

```
{
"c.d":"e",
"a":"b",
"b":"b",
}
```

and I run 

```
var DJ = require("dot-object");
new DJ().object(x)
```

The entry becomes shuffled:

```
{ a: 'b', b: 'b', c: { d: 'e' } }
```

Is there a way to preserve the key order?

**Comment by rhalff** [comment]
This is currently not possible because it operates on the same object.
The key `c.d` is deleted and a new key `c` is created at the next position.

I think the only way to do this is to create a new object, maybe I'll add such an option to a next release.

**Comment by fauria** [comment]
Javascript does not guarantee object property order, as it is intrinsically unordered. More info:  [Does JavaScript Guarantee Object Property Order?](http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order)

**Comment by Tarang** [comment]
@fauria Javascript doesn't guarantee property order on the ECMA spec but in practice node & a couple of browsers do their best to. Its useful when you want to create a JSON document in nodejs in a particular order.
