### ISSUE TITLE
Support variable.names?

### ISSUE THREAD

**Issue by kevin-smets** [rhalff/dot-object#12]
Is there support for variable names with dots in them? E.g.

In:

``` javascript
var obj = {
  "i.am": {
    "an.array": ['a']
  }
};
```

Out:

``` javascript
{
  "i": {
    "am": {
      "an.array": [
        "a"
      ]
    }
  }
}
```

Maybe I'm missing something in the docs, or is there no such thing (yet?)

**Comment by rhalff** [comment]
What happens in your example is this:

In:
```javascript
var obj = {
  "i.am": { "an.array": ['a'] }
};
```

Out:
```javascript
{
  "i": {
    "am": <=== { "an.array": ["a"] }
  }
}
```
`i.am` expands' to `{ i: am: ...}` and is assigned the right hand value.

Which means `an.array`  is never evaluated, it just happens to be part of the object
you want to assign to `{ i: am: ...}`

I think what you are asking for is to have
`{ "i.am.an.array": ['a'] }` expand to `{"i":{"am":{"an.array":["a"]}}}`

The only way to do this at the moment is to choose a different separator.

e.g.
```javascript
var dp = require('dot-object')('|');
var obj = {"i|am|an.array": ['a']};
dp.object(obj);
```
```javascript
{"i":{"am":{"an.array":["a"]}}}
```
