### ISSUE TITLE
Bower install dot-object does not work, dist directory is not downloaded

### ISSUE THREAD

**Issue by tyronedougherty** [rhalff/dot-object#18]
For some reason running `bower install dot-object` does not download the entirety of the `dist` directory. This means that none of the important files are installed. This is what the directory looks like:
<img width="166" alt="screen shot 2016-09-22 at 9 38 59 am" src="https://cloud.githubusercontent.com/assets/4608024/18732672/6d7ef058-80a8-11e6-9176-496415b5e475.png">

Anyone got any ideas?

**Comment by rhalff** [comment]
My bad, I removed the dist folder and added it into .gitignore, I've reverted this and pushed a new release.

Will look at the release process later, to fix it permanently.

**Comment by tyronedougherty** [comment]
All good, thanks for the extremely quick response @rhalff!

**Comment by tyronedougherty** [comment]
Oh by the way I suppose this is a separate issue but the version numbers inside the `bower.json` and `package.json` are different? One is currently `1.5.1` and the other is `1.2.0`.

**Comment by rhalff** [comment]
I fixed that in the last release by manually updating the version in bower.json first.

That's why I have to update the release process, right now I'm using https://github.com/phuu/npm-release which does not update the bower.json automatically.
