### ISSUE TITLE
Can't create a new attribute on the top/root level object

### ISSUE THREAD

**Issue by jonesdhtx** [rhalff/dot-object#19]
It seems you can't create a new attribute on the top/root level object. See the following node console session:

```
dot = require('dot-object')
> x = { a: 1 }
{ a: 1 }
> dot.str('b', 2, x)
{ a: 1 }
> x
{ a: 1 }
```

It only seems to work if you are adding/creating a nested attribute:

```
> x = { a: 1 }
{ a: 1 }
> dot.str('b', 2, x)
{ a: 1 }
> dot.str('b.c', 2, x)
{ a: 1, b: { c: 2 } }
```

**Comment by jonesdhtx** [comment]
I did look through sources and see there is a constructor argument `override` - and noted that fixes the issues if I do the following:

```
> dot = new require('dot-object')('.', /*override:*/true);
DotObject { seperator: '.', override: true, useArray: true, cleanup: [] }
> x = { a: 1 }
{ a: 1 }
> dot.str('b', 2, x)
{ a: 1, b: 2 }
```

Can you explain the purpose of the `override` parameter and if it has any other consequence?

**Comment by rhalff** [comment]
The check for override was wrong in the str() method, I've updated it and pushed a patch release.

I notice the set() method is not described in the documentation, but you might as well use that one.
Currently they are almost the same, the difference being that str() allows a set of modifiers.

`str = function (path, val, obj, mod) `
`set = function (path, val, obj, merge)`

I'll look into joining them so both will have the same signature.
`set = function (path, val, obj, mod, merge)`

**Comment by jonesdhtx** [comment]
Awesome - thanks for the info & the quick fix!

**Comment by msudgh** [comment]
I have a similar issue but a bit different.

Consider the following example as the request's body:

```js
{
  id: "1",
  data: { "x.y": true }
}
```

but `dot.object(req.body)` method is unable to parse it as the below expected:

```js
{
  id: "1",
  data: {
    x: {
      y: true
    }
  }
}
```

Since it works with `dot.object(req.body["data")` case i assume its not going to iterate deeply.

**Comment by TheFoot** [comment]
@msudgh In case it helps you, I created a wrapper module to recursively parse a nested object:

CommonJS Module: (recursive-dot-object.js)
```
const dot = require ( 'dot-object' );

const parseIt = obj => {

    const parsed = dot.object ( obj );

    for ( const [ key, value ] of Object.entries ( parsed ) ) {

        if ( typeof value === 'object' ) {
            parsed[ key ] = parseIt ( value );
        }

    }

    return parsed;

};

module.exports = obj => {
    return parseIt ( obj );
};
```

Test code:
```
const dotParser = require ( './recursive-dot-object' );

const data = {
    request        : {
        query : {
            'scopes.platformOwner': true,
            'scopes.developers'   : true
        },
        params: {
            foo: 'bar'
        }
    },
    'one.two.three': 123
};

console.log (
    JSON.stringify( dotParser ( data ), null, 4)
);
```

Produces:
```
{
    "request": {
        "query": {
            "scopes": {
                "platformOwner": true,
                "developers": true
            }
        },
        "params": {
            "foo": "bar"
        }
    },
    "one": {
        "two": {
            "three": 123
        }
    }
}

```
