### ISSUE TITLE
Force object instead of array

### ISSUE THREAD

**Issue by robecor** [rhalff/dot-object#33]
When we use `dot.object()` is there a way to force numeric values in string to be a field instead of a position from an array?
For example
`{
   "errors.1": "error1",
    "errors.2": "error2",
    "errors.3": "error3"
}`

becomes 
`{errors: ["error1", "error2", "error3"]}`

but I want it to be 
`{errors: {"1": "error1", "2": "error2", "3": "error3"}}`

**Comment by edo386** [comment]
It is possible:

`const Dot = require('dot-object');`
`const dot = new Dot('.', false, false);``

Check the constructor.

**Comment by rhalff** [comment]
Fixed by #31 @robecor thanks for reporting.
