### ISSUE TITLE
Cannot pick value from object if key contains dot

### ISSUE THREAD

**Issue by thierry2015** [rhalff/dot-object#37]
As a developer, I want to be able to pick a value from an object if the key contains dots.

```javascript
// Node JS: 12.5.0
const dot = require('dot-object');

test('Can pick value with dotted key', () => {
    const object = { 'foo.bar': 'baz' };
    expect(dot.pick('foo.bar', object)).toBe('baz');
});
```

Currently, I am receiving `undefined` instead of `baz`.

**Comment by rhalff** [comment]
A key with dots is ambiguous, e.g how should this work:

```javascript
const object = {
  foo: {
    bar: 'baz',
  },
 'foo.bar': 'baz,
}
```
Perhaps adding an escape makes sense? (not currently supported)
```javascript
dot.pick('foo\.bar', object)
```

**Comment by thierry2015** [comment]
I do not think that escaping would make sense since some strings and objects may come from an external source that is not aware of the plugin.

How about this:

```javascript
const object = {
    foo: {
        bar: 'one'
    }
    'foo.bar': 'two',
    'some.thing': 'three'
};

dot.pick('foo.bar', object); // "one"
dot.pick('some.thing', object); // "three"
object['foo.bar']; // "two"
```

We could prefer sub-properties to dotted properties since they are way more frequent. So, if there is an ambiguous situation, this would need additional code by the developer. And I think that it would be simpler to implement.

Until the property cannot be resolved, we go with the next iteration and concatenate the previous key with the current one.

**Comment by rhalff** [comment]
Perhaps it's better to solve it in your own code:
```js
const value = object['foo.bar'] || dot.pick('foo.bar', object);
```
For the other methods like set, move transfer etc. the behavior would become rather unpredictable.

**Comment by cburatto** [comment]
Sorry to reopen this here:

@rhalff you mention "it's better to solve it in your own code" but we don't always know the object schema.
Is it possible to implement the following?

```
const object = {
    foo: {
        bar: 'one'
    },
    'foo.bar': 'two',
    'some': {
        'other.node': {
            is: 'three'
        }
    }
}

let value = dot.pick('some["other.node"].is', object);

// three

```

This is similar to what I would do in code, and it should cover scenarios where the property has spaces and characters that might be used as alternative separators https://github.com/rhalff/dot-object#using-a-different-separator 

This could work interchangeably, even for non-dotted properties:

`dot.pick('foo.bar', object) === dot.pick('["foo"]["bar"]', object) `

`dot.pick('["foo.bar"]', object) === object["foo.bar"]`
