### ISSUE TITLE
delete function issue

### ISSUE THREAD

**Issue by murphyke** [rhalff/dot-object#40]
Am I doing something wrong below with regard to the `delete` function? I am frazzled, so I probably am.

```
$ npm ls | grep dot-object
└─┬ dot-object@1.9.0
$ node
> var dot = require('dot-object')
undefined
> dot.delete('a', {a: 1})
TypeError: dot.delete is not a function
> dot.remove('a', {a: 1})
1
$ node --version
v10.15.3
```

As an aside, there is no `v1.9.0` or `1.9.0` tag, so that doesn't show up as a release on GitHub.

**Comment by rhalff** [comment]
Hi, the delete function was indeed not being exposed correctly. Fixed it in v2.1.0
I've also pushed the tags, including the missing one.

Thanks for reporting.
