### ISSUE TITLE
Array index braces in dot function

### ISSUE THREAD

**Issue by z1m1n** [rhalff/dot-object#42]
The idea is to make configurable array indexes output format. I want to convert object
`some: { array: ['A', 'B'] }` 
like this 
`"some.array[0]": "A",
  "some.array[1]": "B"`
instead of 
`"some.array.0": "A",
  "some.array.1": "B"`

May be it's possible to do now with some settings? If not, I want to submit a PR with this functionality.

**Comment by rhalff** [comment]
You're referring to the dot method right? It doesn't seem to be supported.

For parsing it is supported and it's done automatically without using a setting.

A PR would be great!

preferably with some tests...

The arguments have grown rather ugly btw but I'll try to change that later.
You can just add an extra option similar to as is done for the other options.

**Comment by rhalff** [comment]
I've released a new 2.0.0 version.

I've changed the default to `true`,  so you do not have to set any option.
The option is now named `useBrackets` and can be set to `false` if the no bracket notation is desired.

Thanks again for the pull request.
