### ISSUE TITLE
Support picking array elements

### ISSUE THREAD

**Issue by foobar450** [rhalff/dot-object#5]
I am trying to acheive the following:

```javascript
var data = {
  foo: [
    { text: 'bar1' },
    { text: 'bar2' }
  ]
};

console.log(dot.pick('foo[0].text', data));  // Expected result: 'bar1'
```
However, the current API does not support this. Are there any plans on implementing this feature?
If not, would a pull request for this feature be accepted?  
A similar feature exists in Mongo's API: [positional update](http://docs.mongodb.org/manual/reference/operator/update/positional/)

**Comment by rhalff** [comment]
This is possible using `dot.pick('foo.0.text', data);`, I did not really see the additional benefit of adding bracket notation yet.

However it seems like some sort of check in parseKey could support that notation.

A pull request would be accepted, else I'll maybe add it later.

**Comment by rhalff** [comment]
I've added support for this notation in the new release (0.11.0)

**Comment by foobar450** [comment]
Awesome, thanks!
