### ISSUE TITLE
Trying to redefine non-empty obj[]

### ISSUE THREAD

**Issue by thetutlage** [rhalff/dot-object#8]
I am trying to set value for an existing object like this
## Original Object

``` javascript
var sampleObject = {
 sample : {
  dotted : {
    bar: {
      baz: 'baz'
    }
  }
 }
}
```
## Modifying Here

```
dot.str('sample.dotted.bar',{baz:'boom'},sampleObject)
```

And it returns an error saying Trying to redefine non-empty obj['bar']

**Comment by rhalff** [comment]
you could solve it by adding override=true, but I relialize it should be overwrite, which I did not yet implement.

**Comment by zackiles** [comment]
@rhalff is there a proper way to do what this user is trying to accomplish? Can you also describe what the feature you'd like to do is? I don't mind doing a PR, because I also use dot-object for the functionality this user describes.

**Comment by rhalff** [comment]
If the value only needs to be set you can better use:
```javascript
Dot.set('sample.dotted.bar', {baz: 'boom'}, obj);
```
Which defaults to overwriting the value.

The `str` method is meant to be used with modifiers and initialy was used with string values only.

To use it with that method you can do:
```javascript
dot.override = true;
dot.str('sample.dotted.bar',{baz: 'boom'}, obj);
```

It seems the `set` and `str` methods could be merged though eventually, by having `set` support modifiers.
